
project_id = "qiyjzukzhwklkmpdxmfl"

[functions.submit-business-idea]
verify_jwt = false

[functions.evaluate-business-idea]
verify_jwt = false

[functions.notify-business-evaluation]
verify_jwt = false
