
project_id = "qiyjzukzhwklkmpdxmfl"

[functions.submit-business-idea]
verify_jwt = false

[functions.evaluate-business-idea]
verify_jwt = false

[functions.notify-business-evaluation]
verify_jwt = false

[functions.create-training-payment]
verify_jwt = false

[functions.check-training-availability]
verify_jwt = false
